
server: 
   port: 8080
spring: 
   datasource: 
      url: jdbc:mysql://localhost:3306/liminaldb?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      username: root # change accordingly
      password: Jul@2022105075 # change accordingly
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa: 
      defer-datasource-initialization: true
      show-sql: true
      properties: 
         hibernate: 
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate: 
         naming: 
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         ddl-auto: create
   sql:
    init:
      mode: always
   servlet: 
      multipart: 
         enabled: true
         file-size-threshold: 2KB
         max-file-size: 200MB
         max-request-size: 215MB
   http: 
      multipart: 
         enabled: true
         location: upload

   # security:
   #    jwt:
   #       secret: JdSzro2n0UiXTMMVyqKBLtSDA6dDksWQqGx7D9nwtyA=
   #       expiration: 
   #          hours: 8
   #       issuer: "Liminal"

file: 
   upload: 
      location: ..\\upload-dir
logging: 
   level: 
      com: 
         gabriel: 
            pricems: TRACE
